using System.ComponentModel;

namespace DiGi.BDL.Enums
{
    public enum Variable
    {
        [Description("one-dwelling residential buildings not adapted to permanent residence (PKOB 1110) [m3]")] one_dwelling_residential_buildings_not_adapted_to_permanent_residence_m3 = 746080,
        [Description("non-residential buildings total (PKOB from 1211 to 1274) [m3]")] non_residential_buildings_total_m3 = 746098,
        [Description("hotel buildings (PKOB 1211) [m3]")] hotel_buildings_m3 = 746107,
        [Description("other short-stay accommodation buildings (PKOB 1212) [m3]")] other_short_stay_accommodation_buildings_m3 = 746116,
        [Description("office buildings (PKOB 1220) [m3]")] office_buildings_m3 = 746125,
        [Description("wholesale and retail trade buildings (PKOB 1230) [m3]")] wholesale_and_retail_trade_buildings_m3 = 746134,
        [Description("traffic and communication buildings (PKOB 1241) [m3]")] traffic_and_communication_buildings_m3 = 746143,
        [Description("garage buildings (PKOB 1242) [m3]")] garage_buildings_m3 = 746152,
        [Description("industrial buildings (PKOB 1251) [m3]")] industrial_buildings_m3 = 746161,
        [Description("reservoirs, silos and warehouses (PKOB 1252) [m3]")] reservoirs_silos_and_warehouses_m3 = 746170,
        [Description("buildings for public entertainment (PKOB 1261) [m3]")] buildings_for_public_entertainment_m3 = 746179,
        [Description("museums and libraries (PKOB 1262) [m3]")] museums_and_libraries_m3 = 746188,
        [Description("school, university and research buildings (PKOB 1263) [m3]")] school_university_and_research_buildings_m3 = 746197,
        [Description("hospital or institutional care buildings (PKOB 1264) [m3]")] hospital_or_institutional_care_buildings_m3 = 746206,
        [Description("sports halls (PKOB 1265) [m3]")] sports_halls_m3 = 746215,
        [Description("non-residential farm buildings (PKOB 1271) [m3]")] non_residential_farm_buildings_m3 = 746224,
        [Description("buildings used as places of worship and for religious activities (PKOB 1272) [m3]")] buildings_used_as_places_of_worship_and_for_religious_activities_m3 = 746233,
        [Description("buildings entered into the register of historical monuments and subject to individual protection, immovable archaeological cultural goods (PKOB 1273) [m3]")] buildings_entered_into_the_register_of_historical_monuments_and_subject_to_individual_protection_immovable_archaeological_cultural_goods_m3 = 746242,


        [Description("one-dwelling residential buildings not adapted to permanent residence (PKOB 1110) [m2]")] one_dwelling_residential_buildings_not_adapted_to_permanent_residence_m2 = 746081,
        [Description("residences for communities (PKOB 1130)")] residences_for_communities_m2 = 746090,
        [Description("non-residential buildings total (PKOB from 1211 to 1274) [m2]")] non_residential_buildings_total_m2 = 746099,
        [Description("hotel buildings (PKOB 1211) [m2]")] hotel_buildings_m2 = 746108,
        [Description("other short-stay accommodation buildings (PKOB 1212) [m2]")] other_short_stay_accommodation_buildings_m2 = 746117,
        [Description("office buildings (PKOB 1220) [m2]")] office_buildings_m2 = 746126,
        [Description("wholesale and retail trade buildings (PKOB 1230) [m2]")] wholesale_and_retail_trade_buildings_m2 = 746135,
        [Description("traffic and communication buildings (PKOB 1241) [m2]")] traffic_and_communication_buildings_m2 = 746144,
        [Description("garage buildings (PKOB 1242) [m2]")] garage_buildings_m2 = 746153,
        [Description("industrial buildings (PKOB 1251) [m2]")] industrial_buildings_m2 = 746162,
        [Description("reservoirs, silos and warehouses (PKOB 1252) [m2]")] reservoirs_silos_and_warehouses_m2 = 746171,
        [Description("buildings for public entertainment (PKOB 1261) [m2]")] buildings_for_public_entertainment_m2 = 746180,
        [Description("museums and libraries (PKOB 1262) [m2]")] museums_and_libraries_m2 = 746189,
        [Description("school, university and research buildings (PKOB 1263) [m2]")] school_university_and_research_buildings_m2 = 746198,
        [Description("hospital or institutional care buildings (PKOB 1264) [m2]")] hospital_or_institutional_care_buildings_m2 = 746207,
        [Description("sports halls (PKOB 1265) [m2]")] sports_halls_m2 = 746216,
        [Description("non-residential farm buildings (PKOB 1271) [m2]")] non_residential_farm_buildings_m2 = 746225,
        [Description("buildings used as places of worship and for religious activities (PKOB 1272) [m2]")] buildings_used_as_places_of_worship_and_for_religious_activities_m2 = 746234,
        [Description("buildings entered into the register of historical monuments and subject to individual protection, immovable archaeological cultural goods (PKOB 1273) [m2]")] buildings_entered_into_the_register_of_historical_monuments_and_subject_to_individual_protection_immovable_archaeological_cultural_goods_m2 = 746243,
        [Description("other non-residential buildings not elsewhere classified (PKOB 1274) [m2]")] other_non_residential_buildings_not_elsewhere_classified_m2 = 746252,


        [Description("single-family 1 level [m3]")] single_family_1_level_m3 = 1636387,
        [Description("single-family 2 levels [m3]")] single_family_2_levels_m3 = 1636389,
        [Description("single-family 3 levels [m3]")] single_family_3_levels_m3 = 1636391,
        [Description("single-family 4 levels [m3]")] single_family_4_levels_m3 = 1636393,
        [Description("single-family 5 levels [m3]")] single_family_5_levels_m3 = 1636395,
        [Description("single-family 6 levels [m3]")] single_family_6_levels_m3 = 1636397,
        [Description("single-family 7 levels [m3]")] single_family_7_levels_m3 = 1636399,
        [Description("single-family 8 levels [m3]")] single_family_8_levels_m3 = 1636401,
        [Description("multi-family 1 level [m3]")] multi_family_1_level_m3 = 1636405,
        [Description("multi-family 2 levels [m3]")] multi_family_2_levels_m3 = 1636407,
        [Description("multi-family 3 levels [m3]")] multi_family_3_levels_m3 = 1636409,
        [Description("multi-family 4 levels [m3]")] multi_family_4_levels_m3 = 1636411,
        [Description("multi-family 5 levels [m3]")] multi_family_5_levels_m3 = 1636413,
        [Description("multi-family 6 levels [m3]")] multi_family_6_levels_m3 = 1636415,
        [Description("multi-family 7 levels [m3]")] multi_family_7_levels_m3 = 1636417,
        [Description("multi-family 8 levels [m3]")] multi_family_8_levels_m3 = 1636419,


        [Description("single-family 1 level [pcs]")] single_family_1_level_pcs = 1636386,
        [Description("single-family 2 levels [pcs]")] single_family_2_levels_pcs = 1636388,
        [Description("single-family 3 levels [pcs]")] single_family_3_levels_pcs = 1636390,
        [Description("single-family 4 levels [pcs]")] single_family_4_levels_pcs = 1636392,
        [Description("single-family 5 levels [pcs]")] single_family_5_levels_pcs = 1636394,
        [Description("single-family 6 levels [pcs]")] single_family_6_levels_pcs = 1636396,
        [Description("single-family 7 levels [pcs]")] single_family_7_levels_pcs = 1636398,
        [Description("single-family 8 levels [pcs]")] single_family_8_levels_pcs = 1636400,
        [Description("multi-family 1 level [pcs]")] multi_family_1_level_pcs = 1636404,
        [Description("multi-family 2 levels [pcs]")] multi_family_2_levels_pcs = 1636406,
        [Description("multi-family 3 levels [pcs]")] multi_family_3_levels_pcs = 1636408,
        [Description("multi-family 4 levels [pcs]")] multi_family_4_levels_pcs = 1636410,
        [Description("multi-family 5 levels [pcs]")] multi_family_5_levels_pcs = 1636412,
        [Description("multi-family 6 levels [pcs]")] multi_family_6_levels_pcs = 1636414,
        [Description("multi-family 7 levels [pcs]")] multi_family_7_levels_pcs = 1636416,
        [Description("multi-family 8 levels [pcs]")] multi_family_8_levels_pcs = 1636418,
    }
}
